import serial
import time
import re

# ==========================================
# CONFIGURATION
# ==========================================
SIMULATOR_PORT = '/dev/ttys002'  # The FIRST port generated by socat
LOG_FILE = 'test.txt'          # Change to 'test.txt' to test the other format
BAUD_RATE = 9600
# ==========================================

def parse_hex_to_bytes(line):
    """
    Looks for 8-byte hex payloads in a line of text and converts them to raw bytes.
    Handles both pipe-separated and space-separated formats.
    """
    # 1. Check for pipe format (e.g., 00|20|8A|00|25|00|01|81|)
    pipe_match = re.search(r'((?:[0-9A-Fa-f]{2}\|){8})', line)
    if pipe_match:
        hex_parts = [h for h in pipe_match.group(1).split('|') if len(h) == 2]
        return bytes.fromhex(''.join(hex_parts))

    # 2. Check for space format (e.g., 00 20 8a 00 1e 00 02 81)
    space_match = re.search(r'((?:[0-9A-Fa-f]{2}\s){7}[0-9A-Fa-f]{2})', line)
    if space_match:
        hex_parts = space_match.group(1).split()
        if len(hex_parts) == 8:
            return bytes.fromhex(''.join(hex_parts))

    return None

def run_simulator():
    print(f"Starting generic simulator on {SIMULATOR_PORT}...")
    try:
        with serial.Serial(SIMULATOR_PORT, BAUD_RATE) as ser:
            with open(LOG_FILE, 'r', encoding='cp1252', errors='ignore') as f:
                for line in f:
                    # Extract the raw binary bytes from the text line
                    data_bytes = parse_hex_to_bytes(line)
                    
                    if data_bytes:
                        # Print what we are transmitting so you can visually verify
                        print(f"TX: {data_bytes.hex(' ').upper()}")
                        
                        # Send the raw bytes over the serial port
                        ser.write(data_bytes)
                        
                        # Sleep for 500ms to mimic the hardware timing
                        time.sleep(0.5)
                        
            print("\nFinished reading log file. Transmission complete.")
    except FileNotFoundError:
        print(f"Error: Could not find the file '{LOG_FILE}'")
    except Exception as e:
        print(f"Error: {e}")

if __name__ == '__main__':
    run_simulator()