import serial
import time

# ==========================================
# CONFIGURATION
# ==========================================
SIMULATOR_PORT = '/dev/ttys009'  # IMPORTANT: Change to the FIRST port generated by socat
LOG_FILE = '/Users/kimaruboruett/Documents/shell-eco/realistic/Indy500Dashboard-main/rs232-test/raw-from-rs232.txt'  # Pointing to your new log file
BAUD_RATE = 9600
# ==========================================

def parse_hex_to_bytes(line):
    """Extracts hex characters from the 'Hex Dump:' lines."""
    if line.startswith("Hex Dump:"):
        # Strip out the prefix and any extra whitespace
        hex_str = line.replace("Hex Dump:", "").strip()
        # Remove spaces between the hex pairs and convert to raw bytes
        return bytes.fromhex(hex_str.replace(" ", ""))
    return None

def run_simulator():
    print(f"Starting fragmented simulator on {SIMULATOR_PORT}...")
    try:
        with serial.Serial(SIMULATOR_PORT, BAUD_RATE) as ser:
            with open(LOG_FILE, 'r', encoding='utf-8', errors='ignore') as f:
                for line in f:
                    data_bytes = parse_hex_to_bytes(line)
                    
                    if data_bytes:
                        print(f"TX (Fragment): {data_bytes.hex(' ').upper()}")
                        
                        # Send the raw, fragmented bytes over the serial port
                        ser.write(data_bytes)
                        
                        # Sleep briefly to mimic the hardware's 1kHz staggered output
                        time.sleep(0.1)
                        
            print("\nFinished reading log file. Transmission complete.")
    except FileNotFoundError:
        print(f"Error: Could not find the file '{LOG_FILE}'")
    except Exception as e:
        print(f"Error: {e}")

if __name__ == '__main__':
    run_simulator()